# Generated by Django 3.1 on 2020-08-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='username', max_length=45, null=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=45, null=True)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
